services:
  php:
    build:
      context: .
      target: web
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: mlc_app
    environment:
      APP_ENV: ${APP_ENV:-prod}
      DATABASE_URL: ${DATABASE_URL}
      MAILER_DSN: ${MAILER_DSN}
      TRUSTED_PROXIES: REMOTE_ADDR
    networks:
      - mlc_network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - mlc_config:/var/matchsettings
      - mlc_thumbs:/var/www/app/public/uploads

  nginx:
    build:
      context: .
      target: nginx
    container_name: mlc_server_web
    environment:
      NGINX_HOST: ${NGINX_HOST:-localhost}
      PHP_FPM_HOST: ${PHP_FPM_HOST:-php}
      VITE_HOST: ${VITE_HOST:-localhost}
    networks:
      - mlc_network
      - proxy
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - mlc_thumbs:/var/www/app/public/uploads/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # HTTP
      - "traefik.http.routers.mlc.entrypoints=http"
      - "traefik.http.routers.mlc.rule=Host(`mlc.tmnf.fr`) || Host(`www.mlc.tmnf.fr`)"
      - "traefik.http.routers.mlc.middlewares=https-redirect"
      # HTTPS
      - "traefik.http.routers.mlc-secure.entrypoints=https"
      - "traefik.http.routers.mlc-secure.rule=Host(`mlc.tmnf.fr`) || Host(`www.mlc.tmnf.fr`)"
      - "traefik.http.routers.mlc-secure.tls=true"
      - "traefik.http.routers.mlc-secure.tls.certresolver=letsencrypt"
      # Middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # Logging
      - "logging.enabled=true"
      - "logging.service=mlc-nginx"

  database:
    image: mysql:8.4.8
    container_name: mlc_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mlc_app}
      MYSQL_USER: ${MYSQL_USER:-mlc_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mlc_password}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mlc_database
      - mlc_network
      - proxy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5m
    restart: unless-stopped

  messenger:
    build:
      context: .
      target: worker
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: mlc_messenger
    environment:
      APP_ENV: ${APP_ENV:-prod}
      DATABASE_URL: ${DATABASE_URL}
      MAILER_DSN: ${MAILER_DSN}
    networks:
      - mlc_network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

networks:
  proxy:
    external: true
  mlc_network:
    driver: bridge
  mlc_database:
    external: true

volumes:
  db_data:
  mlc_config:
  mlc_thumbs: