# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# All routes with locale prefix
# Routes without locale (e.g. /profile) are automatically redirected to /fr/profile
# by LocaleRedirectSubscriber
controllers:
    resource: routing.controllers
    prefix: /{_locale}
    requirements:
        _locale: fr|en
    defaults:
        _locale: fr
