framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/styles/*'
        # Mode 'ignore' because Tailwind CSS imports are handled by Vite, not AssetMapper
        missing_import_mode: ignore

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
